baseURL: "http://coffmanfam.com/"
languageCode: "en-us"
title: "Coffman Fam"
theme: "PaperMod"

timeout: 20000

params:
  author: admin
  author_name: Josh C
  nav_items: 1
  index_items: 6
  iso8601: "2006-01-02T15:04:05"

summaryLength: 40

staticDir: "static"

buildFuture: true

enableRobotsTXT: false

rssLimit: 10000

menu:
  main:
  - identifier: about
    name: about
    url: /about/
    weight: -110
  - identifier: posts
    name: posts
    url: /posts/
    weight: -110
